# Generated by Django 2.2.1 on 2020-03-17 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='com_1968',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Libelle_de_commune', models.TextField(blank=True, null=True)),
                ('Departement_en_geographie_2018', models.TextField(blank=True, null=True)),
                ('De_20_a_24_ans_Femmes_RP1968', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='com_1975',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Libelle_de_commune', models.TextField(blank=True, null=True)),
                ('Departement_en_geographie_2018', models.TextField(blank=True, null=True)),
                ('De_20_a_24_ans_Femmes_RP1975', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='com_1982',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Libelle_de_commune', models.TextField(blank=True, null=True)),
                ('Departement_en_geographie_2018', models.TextField(blank=True, null=True)),
                ('De_20_a_24_ans_Femmes_RP1982', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='com_1990',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Libelle_de_commune', models.TextField(blank=True, null=True)),
                ('Departement_en_geographie_2018', models.TextField(blank=True, null=True)),
                ('De_20_a_24_ans_Femmes_RP1990', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='com_1999',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Libelle_de_commune', models.TextField(blank=True, null=True)),
                ('Departement_en_geographie_2018', models.TextField(blank=True, null=True)),
                ('De_20_a_24_ans_Femmes_RP1999', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='com_2006',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Libelle_de_commune', models.TextField(blank=True, null=True)),
                ('Departement_en_geographie_2018', models.TextField(blank=True, null=True)),
                ('De_20_a_24_ans_Femmes_RP2006', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='com_2011',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Libelle_de_commune', models.TextField(blank=True, null=True)),
                ('Departement_en_geographie_2018', models.TextField(blank=True, null=True)),
                ('De_20_a_24_ans_Femmes_RP2011', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='com_2016',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Libelle_de_commune', models.TextField(blank=True, null=True)),
                ('Departement_en_geographie_2018', models.TextField(blank=True, null=True)),
                ('De_20_a_24_ans_Femmes_RP2016', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
